MONGODB: 
  URL: mongodb+srv://Celeste:Celeste@cluster0.gwsvg.mongodb.net/myFirstDatabase

JWT:
  SECRET: secretKey
  EXPIRATION_TIME: 3d

CLOUDINARY:
  NAME: dhl6bbmhb
  KEY: 944161134181937
  SECRET: -R8go378CswcnQbjnrSKAnzD1Yk